version: b{build}

environment:
  nodejs_version: "8"

os: unstable

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:
  GH_TOKEN:
    secure: febq/MqfzS/3JfchQVtlarZApEi80xRea6Z5qvUTYeb1vH8ByxIXqavTh6DIo53/

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install
  - yarn add jquery
  - yarn add popper.js

build_script:
  - yarn run build
  - yarn run package-win

notifications:
  - provider: Slack
    auth_token:
      secure: 8igb/45j7jFO/0zlLOXgvxk6AQzx68GVkMrY17G8sDhMXkofJ3jnqF6qT204DLdI7RrL5rNUt9WspyagZrzL/Gt3SVaenCd6xx7S8VQz/sk=
    channel: '#builds'
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
